name: flutter_blue_example
description: Demonstrates how to use the flutter_blue plugin.
publish_to: 'none'

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_blue: 0.6.2

flutter:
  uses-material-design: true