/// Flutter icons EcoFootprint
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  EcoFootprint
///      fonts:
///       - asset: fonts/EcoFootprint.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class EcoFootprint {
  EcoFootprint._();

  static const _kFontFam = 'EcoFootprint';

  static const IconData footprint = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData water_drop = const IconData(0xe801, fontFamily: _kFontFam);
}
